on: [push]
name: Create an issue on push
permissions:
  contents: read
  issues: write 
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: Test
        uses: dblock/create-a-github-issue@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_URL: testurl
          PR_FROM_SHA: commitId
          PR_USER: '${{ github.event.head_commit.author.username }}'
          PUSH_USER: '${{ github.triggering_actor }}'
        with:
          filename: .github/ISSUE_TEMPLATE/failed_check.md
              
